In [13]:
import pandas as pd

# Đọc dữ liệu từ tệp CSV
df = pd.read_csv("/content/drive/MyDrive/project_facebook_bigdata/omg/lable_data.csv")

# Kiểm tra dữ liệu
print(df.head())

   id                                            content  label
0   1                                         id,message      2
1   2  0,"Xinh như vậy mà bị gọi là ""hoa nhài cắm bã...      1
2   3                1,Bông Hoa Nhài Cắm Bãi Chubin Trâu      2
3   4                                      2,Chúc mừng        0
4   5                                          3,Minh Tú      2


In [14]:
import pandas as pd
import numpy as np
import nltk
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer

# Đọc dữ liệu từ tệp CSV
df = pd.read_csv("/content/drive/MyDrive/project_facebook_bigdata/omg/lable_data.csv")

# Đọc stopwords Tiếng Việt từ tệp stopwordvietnamese.txt
with open("/content/vietnamese-stopwords.txt", "r", encoding="utf-8") as f:
    stopwords = f.read().splitlines()

# Xóa dòng có giá trị np.nan trong cột 'content'
df = df.dropna(subset=['content'])

# Tiền xử lý dữ liệu
nltk.download('punkt')
vectorizer = TfidfVectorizer(
    lowercase=True,
    stop_words=stopwords,
    tokenizer=nltk.word_tokenize
)
X = vectorizer.fit_transform(df['content'])
y = df['label']



[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/feature_extraction/text.py:409: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['a', 'bao', 'bay', 'biến', 'biệt', 'bây', 'bõm', 'bảo', 'bất', 'bẩy', 'bập', 'bắt', 'bội', 'chao', 'chi', 'chia', 'chu', 'chui', 'chuẩn', 'chà', 'chành', 'chí', 'chót', 'chùn', 'chăn', 'chũn', 'chưng', 'chạnh', 'chả', 'chầm', 'chầy', 'chập', 'chắn', 'chẳng', 'chết', 'chốc', 'chừ', 'chừng', 'coi', 'cu', 'cá', 'câu', 'cóc', 'công', 'cạnh', 'cảm', 'cầu', 'cật', 'cắt', 'cổ', 'cụ', 'cục', 'cực', 'da', 'dà', 'dĩ', 'dưng', 'dần', 'dầu', 'dịp', 'dở', 'dụng', 'gian', 'giá', 'giác', 'giời', 'ha', 'hiện', 'ho

In [15]:
# Chia dữ liệu thành tập huấn luyện và tập kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)




In [16]:
# Huấn luyện mô hình Naive Bayes
model = MultinomialNB()
model.fit(X_train, y_train)



MultinomialNB()

In [17]:
# Đánh giá mô hình
y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Độ chính xác:", accuracy)

report = classification_report(y_test, y_pred)
print("Báo cáo phân loại:\n", report)

conf_matrix = confusion_matrix(y_test, y_pred)
print("Ma trận nhầm lẫn:\n", conf_matrix)

Độ chính xác: 0.743050856819343
Báo cáo phân loại:
               precision    recall  f1-score   support

           0       0.74      0.41      0.53     38984
           1       0.56      0.00      0.01     10205
           2       0.74      0.96      0.84     95649

    accuracy                           0.74    144838
   macro avg       0.68      0.46      0.46    144838
weighted avg       0.73      0.74      0.70    144838

Ma trận nhầm lẫn:
 [[16091     3 22890]
 [ 1637    47  8521]
 [ 4131    34 91484]]
